name: Build EFI

on: [push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run:  ./install_deps.sh
    - name: Complete Build
      run:  ./0A_complete_build.sh
